# Generated by Django 5.2.8 on 2025-12-04 15:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Comentario sobre el destino (máximo 1000 caracteres)', max_length=1000, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(help_text='Destino al que pertenece la review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='relecloud.destination', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Calificación del destino (entre 1 y 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='Usuario que escribió la review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='relecloud_r_created_df46dc_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['destination', '-created_at'], name='relecloud_r_destina_c584b3_idx'),
        ),
    ]
