# Generated by Django 5.2.8 on 2025-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0003_alter_review_comment_alter_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
