# Generated by Django 5.2.9 on 2025-12-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_destination_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inforequest',
            options={'ordering': ['-id'], 'verbose_name': 'Solicitud de información', 'verbose_name_plural': 'Solicitudes de información'},
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del destino (opcional)', null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='cruise',
            field=models.ForeignKey(error_messages={'blank': 'Por favor, seleccione un crucero.', 'null': 'Debe seleccionar un crucero.', 'required': 'Debe seleccionar un crucero de la lista.'}, help_text='Seleccione el crucero sobre el que desea información', on_delete=django.db.models.deletion.PROTECT, to='relecloud.cruise', verbose_name='Crucero de interés'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Por favor, ingrese su correo electrónico.', 'invalid': 'Ingrese un correo electrónico válido (ejemplo: usuario@dominio.com).', 'null': 'El correo electrónico es obligatorio.', 'required': 'El correo electrónico es un campo obligatorio.'}, help_text='Ingrese un correo electrónico válido', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='name',
            field=models.CharField(error_messages={'blank': 'Por favor, ingrese su nombre completo.', 'max_length': 'El nombre no puede tener más de 50 caracteres.', 'null': 'El nombre es obligatorio.', 'required': 'El nombre es un campo obligatorio.'}, help_text='Ingrese su nombre completo (máximo 50 caracteres)', max_length=50, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='inforequest',
            name='notes',
            field=models.CharField(error_messages={'blank': 'Por favor, déjenos un mensaje con su consulta.', 'max_length': 'El mensaje no puede tener más de 2000 caracteres.', 'null': 'El mensaje es obligatorio.', 'required': 'El mensaje es un campo obligatorio.'}, help_text='Déjenos su consulta o comentario (máximo 2000 caracteres)', max_length=2000, verbose_name='Mensaje'),
        ),
    ]
